name: publish

on:
  push:
    branches: [ dev ]

jobs:
  publish-boranga-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Boranga Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u GraemeMuller --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
