name: Publish Boranga

on:
  release:
    types: [created]

jobs:
  publish-boranga-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/GraemeMuller/boranga.dev:latest
        docker run ghcr.io/GraemeMuller/boranga.dev:latest
        docker push ghcr.io/GraemeMuller/boranga.dev:latest
